### ISSUE TITLE
Error while using "fitImage with initramfs"

### ISSUE THREAD

**Issue by Sourabh1107** [dh-electronics/dhcom_stm32mp1-bsp-platform#2] opened 2021-12-08 10:52 UTC
Hi,

When I try to bitbake core-image-swupdate I get the following error:

ERROR: /root/sources/meta-python2/recipes-devtools/python/python_2.7.18.bb: Unable to determine endianness for architecture 'INVALID'                                                                                        | ETA:  --:--:--
ERROR: /root/sources/meta-python2/recipes-devtools/python/python_2.7.18.bb: Please add your architecture to siteinfo.bbclass
ERROR: Failed to parse recipe: /root/sources/meta-python2/recipes-devtools/python/python_2.7.18.bb

Can you please let me know what is the reason for it?

**Comment by mschmoeller** [comment] 2021-12-13 11:12
Hi, 
is this issue solved by taking the correct machine config?

**Comment by Sourabh1107** [comment] 2021-12-13 11:54
Hi, 

Yes, its resolved. I am using dh-stm32mp1-dhcor-avenger96 as MACHINE.

And also I wanted to understand few things.
1. core-image-swupdate: This recipe is using swupdate-image.inc to include swupdate and swupdate-www packages. I have modified local.conf to include `IMAGE_FSTYPES = "tar.gz ext4 ext4.gz"`. 
2. Which recipe should I use to generate .swu file? Is there any example recipe available? I could see swupdate-handler.bb recipe but does this generate .swu file?
3. And also how can I access SWUpdate using menuconfig?
4. The structure of .swu file should be: "sw-description image.tar.gz swupdate-handler.sh". Is this right?
5. swupdate-handler.sh will check for "dh-preupdate.sh" and "dh-postupdate.sh". What are these scripts for?

**Comment by mschmoeller** [comment] 2021-12-13 12:11
Hi, 
since the issue is solved, I would suggest to close it.
I'm going to send you the information on your other topics via e-mail.

**Closed as completed by mschmoeller** 2021-12-13 12:11 UTC
